#!/bin/bash
# Give this to condor_submit
# See Hello World on HTCondor http://chtc.cs.wisc.edu/helloworld.shtml
# condor_submit -i to get interactive job without max wall time
# condor_submit wid-logistic_regression-tox21.sub
# condor_status to dump slots
# condor_rm to kill your jobs
# condor_q to do a 'qstat'

#PBS -N mmnt-jbf-log-reg-tox21

# Have to make *.sh executable
# HTCondor will execute this script once your job is assigned to a machine
Executable = wid-stnn_dbn-dude.sh
# Leave as vanilla
Universe = vanilla

# Disable notifications for now
Notification = Never
Notify_user = feriante@cs.wisc.edu

#PBS -j oe
# Set up a path to error and output, can use these special HTCondor env variables
# to name files if you want
Output = stnn_dbn-dude.$(Cluster).$(Process).out
Error = stnn_dbn-dude.$(Cluster).$(Process).err  
Log = stnn_dbn-dude.$(Cluster).$(Process).log

#PBS -l nodes=1:ncpus=1,mem=2gb,walltime=10:00:00
# HTCondor machine requirements http://research.cs.wisc.edu/htcondor/manual/v7.6/2_5Submitting_Job.html#sec:user-man-req-and-rank
# Full list of attributes available http://research.cs.wisc.edu/htcondor/manual/v7.6/10_Appendix_A.html#sec:Job-ClassAd-Attributes
# Can also use "Requirements = " for more attributes
# Prefer to run on the Virology exec nodes in the WID pool, probably want to do this for the multitask jobs
# For single task, could drop this or prefer MachineOwner != "Virology"
Rank = MachineOwner == "Virology"
# Use defaults for disk and memory
Request_cpus = 1
Request_memory = 3GB
# Don't remember how to set the wall time

# Copy the Cluster and Process and the machine that runs the job
Environment = "cluster=$(Cluster) process=$(Process) runningon=$$(Name)"

#PBS -t 0-11
# Queue I instances of the executable, each one will have a Process id in the range
# [0, I-1]
Queue 102
#END