###################################################################
#
# Submit a small Python test script to see if Theano loads
# Run on the WID pool, with preference to use the Virology machines
# Assume a shared file system
# See http://research.cs.wisc.edu/htcondor/manual/v7.6/condor_submit.html
# condor_q is like qstat in PBS
# 
###################################################################

# Have to make *.sh executable
Executable = wid_test_theano.sh
Universe = vanilla

# Disable notifications for now
Notification = Never
Notify_user = gitter@biostat.wisc.edu

Output = $(Cluster).$(Process).out
Error = $(Cluster).$(Process).err  
Log = $(Cluster).$(Process).log

# Prefer to run on the Virology exec nodes in the WID pool but don't require it
Rank = MachineOwner == "Virology"
# Use defaults for disk and memory
Request_cpus = 1

# Copy the Cluster and Process and the machine that runs the job
Environment = "cluster=$(Cluster) process=$(Process) runningon=$$(Name)"

Queue 2
#END
